[env:heltec_wifi_lora_32_V2]
platform  = espressif32
board     = heltec_wifi_lora_32_V2
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
  sandeepmistry/LoRa@^0.8.0
  olikraus/U8g2@^2.35.9
  bblanchon/ArduinoJson@^7.0.0
  knolleary/PubSubClient@^2.8
  tzapu/WiFiManager@^2.0.17